###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:h2:~/bookkeeper
    init:
      platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          batch_size: 50

logging:
  level:
    root: INFO

javafx:
  title: Bookkeeper
  stage:
    width: 800
    height: 600
    resizable: true